### ISSUE TITLE
bofa not asking mfa and sending email instead

### ISSUE THREAD

**Issue by mritchie712** [plaid/support#134]
When I try use connect for bofa, I don't get any mfa's, instead it is sending me an email, how can I fix this?

```connect = client.connect(account_type='bofa', username='xxx', password='xxx', email='x@gmail.com')```

response
```{u'access_token': 'xxx', u'mfa': {u'message': u'Code sent to x@gmail.com'}, u'type': u'device'}```

The email has an "Authorization code" in it, but I'm not sure how to use it.  I do not have SafePass enabled.

**Comment by ctrembl** [comment]
When it comes to [MFA](https://plaid.com/docs/#institutions) for Bank of America accounts, you may encounter either questions or a code. Since it is Bank of America that determines which type of MFA is required for a particular account and not Plaid, it is likely that Safepass is in fact enabled for your account to some extent.

In order to handle code-based MFA, you will need to respond with the code in the `mfa` field of a `/connect/step/` request. You can read all about code-based MFA in our documentation [here](https://plaid.com/docs/#mfa-authentication).
