### ISSUE TITLE
Standardized Transaction Names

### ISSUE THREAD

**Issue by TrySpaceCo** [plaid/support#146]
Plaid provides name key value pair in the transactions array.  Is the name of a given vendor standardized across banks?  To be more clear, in the case of a vendor like Chipotle, might American Express refer to it as 'Chipotle' and Bank of America refer to it as Chipotle Mexican or does Plaid control for this and provide one name for it?

**Comment by TrySpaceCo** [comment]
The docs say that webhook transactions will be updated throughout the day.  Does that include Sundays and holidays or is it just business hours Monday thru Friday or something else?

**Comment by michaelckelly** [comment]
@TrySpaceCo:

Each institution reports transaction data in a different format. Every effort is made to standardize the data associated with each transaction (so, ideally, "Chipotle" would *always* be just "Chipotle") but inconsistencies can still exist simply due to the unreliable and unpredictable nature of the the data.
