### ISSUE TITLE
Get Institution by Type

### ISSUE THREAD

**Issue by ellardli** [plaid/support#148]
Hi,

Are there plans for having an endpoint for getting an institution by type ('wells', 'cit', etc)? Alternatively, are there any plans on being able to do an Auth using an institution's ID instead of type? It's not a huge deal but it would be nice if I just had to keep track of one or the other instead of both of them.

Thanks.

**Comment by ctrembl** [comment]
Hey @ellardli - apologies for the delayed response here.

Can you clarify what you mean by 'getting an institution by type'? We currently have an [Institutions endpoint](https://plaid.com/docs/#institutions) that allows you to retrieve detailed information on the institutions currently supported by Plaid. Are you asking about having an endpoint that is specific to the type `/institutions/:type` instead of the id `/institutions/:id`?

At the moment, we don't have any plans to allow institution ids instead of types. Other than checking the institutions endpoint for new institutions, there shouldn't be any need to utilize the institution ids. I would be curious to learn how else you intend to utilize the institution ids.

Let me know if you have any other questions.
