### ISSUE TITLE
Account not supported error

### ISSUE THREAD

**Issue by sahilkataria** [plaid/support#150]
One of our clients gets a "This account is currently not supported" error (1210) with a BofA account. I understand that one of the reasons we can get this is when SafePass is enabled. But that has its own specific error code (1211). What are the other possible reasons we can see this error?

Regards
Sahil

**Comment by ctrembl** [comment]
Hey Sahil - As you mentioned, the most common culprit of this error is SafePass accounts that have additional security settings associated with them. In some cases, you may receive a 1210 instead of a 1211 for this.

If you are encountering either of these errors for an account that you have additional questions on, feel free to email the access token over to support@plaid.com with a quick description of the issue!
