### ISSUE TITLE
Transactions coming in without 'pending' attribute

### ISSUE THREAD

**Issue by pgorsira** [plaid/support#167]
Hey guys,

Started seeing this yesterday and today. We have about 80 transactions coming in for one user that do not have a `pending` attribute. Is this a bug? Should we assume these are posted? They show up when we request txns with `pending: true` and when we leaving the `pending` parameter out of the request (so only posted are supposed to be returned). This would leave me to believe that they are posted txns but I'm scared to totally conclude that.

Can provide transaction IDs/access tokens/etc upon request. Thx!

**Comment by ctrembl** [comment]
Hey @pgorsira -- thanks for bringing this to our attention. If you could send over some transaction IDs and access tokens to support@plaid.com, we'll take a closer look!

**Comment by pgorsira** [comment]
Cool, sent

**Comment by ctrembl** [comment]
__Resolved!__ This account was affected by both a lack of _pendingTransaction ids for recent transactions (due to the account not being updated properly), along with the lack of the pending field for old transactions. The root of this problem was discovered and a fix has now been deployed into production.
