### ISSUE TITLE
[Question]: Using Plaid in Scheduler

### ISSUE THREAD

**Issue by jaymehtasa** [plaid/support#171]
Hello All,

We are implementing an application where we have to fetch user's daily transactions in a scheduler on Server runs every night, so questions,

* Can we store Access Token to Server DB? if Yes, is it safe? If NO, how can we use Plaid in scheduler?
* What is the life of Access Token, We are authenticating user from a mobile application and planning to  store Access token in Server DB.
* In what cases Access Token gets expired?
* If someone change their bank (institute) password, access token will expired automatically?
* Can someone give example response for failed API because of invalid/expired access token?

Thanks.

**Comment by ctrembl** [comment]
__Can we store Access Token to Server DB? if Yes, is it safe? If NO, how can we use Plaid in scheduler?__

Yes, it is safe to store access tokens locally as long as your API keys are being passed into your application securely as environmental variables. Storing these tokens is highly recommended - if not required - as all future API interactions for a user require the input of an access token. 

__What is the life of Access Token, We are authenticating user from a mobile application and planning to store Access token in Server DB. In what cases Access Token gets expired?__

Access tokens are valid indefinitely or until a user is removed using a `DELETE` call to the API.

__If someone change their bank (institute) password, access token will expired automatically?__

No, the access token will remain valid for the user. Instead, we will return an error code indicating that the user needs to update their password with Plaid. To update their information accordingly, you'll want to send a [`PATCH`](https://plaid.com/docs/#update-user) request with the updated password and existing access token.

__Can someone give example response for failed API because of invalid/expired access token?__

A full list of Plaid error codes can be found in our documentation [here](https://plaid.com/docs/#response-codes). `1105` is our "bad access token" error.

Let us know if you have any other questions!

**Comment by jaymehtasa** [comment]
Thanks Carl.

> Can we store Access Token to Server DB? if Yes, is it safe? If NO, how can we use Plaid in scheduler?

> Yes, it is safe to store access tokens locally as long as your API keys are being passed into your application securely as environmental variables. Storing these tokens is highly recommended - if not required - as all future API interactions for a user require the input of an access token.

To be clear, Mobile app will call *connect* end-point and get access token, access token will transport over http to Node JS back-end and will be stored in Mongo Database for future use, it's not about storing locally on Mobile device, now is it safe to store on remote DB for future use in Cronjob(Scheduler)?

Let me know please?

**Comment by ctrembl** [comment]
Yes, the configuration you mentioned is correct.

**Comment by jaymehtasa** [comment]
Ok Thanks! Appreciate your prompt response.

**Comment by Pengo26** [comment]
Would it be considered safe to expose the access token in the URL?
