### ISSUE TITLE
Bank of America old password

### ISSUE THREAD

**Issue by steaks** [plaid/support#179]
I am testing a Bank of America account.  I noticed that when I enter an old password I get a 201 (MFA required).  Then when I enter the correct MFA response I get response 402 code 1202 (The password provided was not correct).  Is this behavior intended?  Are we not receiving a 402 on the first request for security reasons?

**Comment by Anu2g** [comment]
+1

**Comment by ctrembl** [comment]
This is the result of a credential validation process unique to Bank of America. As long as the username is valid, Bank of America automatically proceeds to the first security question associated with the account. Only after the security question is submitted (correct or otherwise) is the password validated and an invalid password error thrown if applicable.

It's certainly a strange process that may cause confusion, but unfortunately something that is controlled by and required on the bank's side.

**Comment by Anu2g** [comment]
Thanks for the quick reply

**Comment by steaks** [comment]
Thanks @ctrembl!
