### ISSUE TITLE
Webhooks and real bank accounts on tartan.plaid.com

### ISSUE THREAD

**Issue by andyburke** [plaid/support#210]
Hi,

When I used one of the test accounts, I almost immediately get a webhook callback (barring issue #209).

However, we just tested linking a real bank account through tartan.plaid.com and after 1 hour have not received a webhook callback.

Is this expected behavior?

**Comment by andyburke** [comment]
The webhook was eventually called, but it was well over an hour. Is that expected for the sandbox? Will that be different in production?

**Comment by michaelckelly** [comment]
@andyburke - In future, please feel free to reach out to support@plaid.com when investigating issues such as this - when doing so, please include the API access token or some other API identifier.

Webhooks may be delayed due to instability at the financial institution level. Plaid automatically retries transaction updates over time when these situations are encountered.
