### ISSUE TITLE
Balance updating without receiving a webhook?

### ISSUE THREAD

**Issue by nicksergeant** [plaid/support#231]
I'm seeing balances update across requests to `/connect/get` but have confirmed that I'm not receiving a webhook indicating that transactions have been pulled (I did receive the initial confirmation webhook). A few questions:

1. Do balances update separately from transaction pulls?
2. Can you send a webhook when the balance updates, so we can make a request and get the most updated balance as soon as it's available?

Without a webhook indicating a balance change, we're forced to keep a cronjob hitting `/balance` to keep things up to date.

**Comment by clintbxtreme** [comment]
I too am looking for a webhook when the balance is updated.

**Comment by michaelckelly** [comment]
Plaid sends a code 2 webhook whenever new transactions are pulled for an access token with Connect enabled. If you have questions about a specific access token, please reach out to support@plaid.com - please include the affected access_token or any other API identifier so that we can investigate.

Also - please feel free to direct questions such as this to support@plaid.com, which is monitored more often than this!
