### ISSUE TITLE
Great Lakes Student Loan Accounts are not returning transactions

### ISSUE THREAD

**Issue by brentoneill** [plaid/support#254]
After linking a Great Lakes Student Loan Account, I am unable to retrieve transactions from the account

**Comment by michaelckelly** [comment]
@brentoneill  - Plaid's Connect product supports transactions for `credit` and `depository` type accounts. In future, please feel free to reach out to support@plaid.com with questions such as this - please include an `access_token` or other API identifier in your request so that we can more efficiently help you.
